name: Deploy Cloud Function with WIF

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        workload_identity_provider: "projects/937980401410/locations/global/workloadIdentityPools/github-pool1/providers/github-provider"
        service_account: "github-actions-test@gcp-5ann01-sbx-devopspoc.iam.gserviceaccount.com"

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
     
    - name: Debug Secrets
      run: |
        echo "Checking EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}"
        echo "Checking EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}"
        echo "Checking EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}"
        echo "Checking EMAIL_SMTP: ${{ secrets.EMAIL_SMTP }}"
        echo "Checking EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}"
   
    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy send_notification \
          --gen2 \
          --runtime python310 \
          --trigger-topic my-topic \
          --entry-point send_notification \
          --source . \
          --region=us-central1 \
          --set-env-vars="username=${{ secrets.EMAIL_USERNAME }},password=${{ secrets.EMAIL_PASSWORD }},sender=${{ secrets.EMAIL_SENDER }},SMTP=${{ secrets.EMAIL_SMTP }},recipients=${{ secrets.EMAIL_RECIPIENTS }}"
